[tool.poetry]
name = "nlp"
version = "0.1.0"
description = ""
authors = ["Quentin <synkx@hotmail.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
spacy = "^3.5.1"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
